name: Build and release k3s-cuda image

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache k3s build
        uses: actions/cache@v3
        id: cache-k3s-build
        with:
          path: k3s/build
          key: ${{ runner.os }}-k3s-build-release-1.26-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-k3s-build-release-1.26-
            ${{ runner.os }}-k3s-build-

      - name: Test cache
        id: test-cache
        run: |
          if [ -f k3s/build/out/data.tar.zst ]; then
            echo "::set-output name=cache-hit::true"
          else
            echo "::set-output name=cache-hit::false"
          fi

      - name: Clone k3s
        uses: actions/checkout@v3
        if: steps.test-cache.outputs.cache-hit != 'true'
        with:
          repository: rancher/k3s
          path: k3s
          ref: release-1.26

      - name: Compile k3s
        if: steps.test-cache.outputs.cache-hit != 'true'
        run: |
          cd k3s
          mkdir -p build/data && ./scripts/download && go generate
          SKIP_VALIDATE=true make
          cd ..
          unzstd k3s/build/out/data.tar.zst

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Docker Meta
        uses: crazy-max/ghaction-docker-meta@v2
        id: docker_meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/k3s-cuda
          tags: |
            latest
            type=sha,prefix=sha-,format=short

      - name: Authenticate to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to GHCR
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
